### PR TITLE
Provide hsqldb database support (issue 303)

### PR DESCRIPTION
**Pull request by Query-Interface**
Issue: https://github.com/spring-projects-experimental/spring-graalvm-native/issues/303

Add a new hint _HSQLDBHints_ to import required class and resources.

Add a substitute to **hsqlb** class _FrameworkLogger_. This class attempts to retrieve log configuration at runtime but cannot find them since the property _java.home_ is not set (see https://sourceforge.net/p/hsqldb/src/org/
hsqldb/lib/FrameworkLogger.java#l364).
To workaround this issue the method _isDefaultJdkConfig_ is overriden.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Query-Interface Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects-experimental/spring-graalvm-native&pullRequestId=395)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects-experimental/spring-graalvm-native&pullRequestId=395) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Query-Interface Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects-experimental/spring-graalvm-native&pullRequestId=395)!

**Comment by sdeleuze** [comment]
Thanks a lot I will review and hopefully merge it next week.

**Comment by sdeleuze** [comment]
Merged via 16a5bed878ba364a431757a577352fb78994ff15 thanks for your contribution.

**Pull request closed without merging**
